# Generated by Django 5.2 on 2026-04-14 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accaunts', '0002_remove_customuser_username_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
