# Generated by Django 4.2.16 on 2026-01-27 14:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0004_rating_alter_book_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='author',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('book', 'user')},
        ),
    ]
