# Generated by Django 4.2.16 on 2026-01-27 15:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0005_rename_author_rating_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='user',
            new_name='author',
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('book', 'author')},
        ),
    ]
