# Generated by Django 4.2.16 on 2026-01-28 16:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0006_rename_user_rating_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='favorites',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
