# Generated by Django 4.2.16 on 2026-01-28 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_book_favorites_book_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='like',
            new_name='likes',
        ),
    ]
