# Generated by Django 5.2 on 2026-04-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_remove_book_favorites_book_favourites_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='url',
            field=models.URLField(blank=True, default=None, null=True, unique=True),
        ),
    ]
